version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
    - ./pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: on-failure
    volumes:
      - /redis-data:/var/lib/redis
    ports:
      - 6379:6379

  bot:
    container_name: bot
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
